services:
  nextjs:
    build: .
    environment:
      WATCHPACK_POLLING: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Map our directory to the Docker /app directory
      - /app/node_modules # Prevents overwriting node_modules in the container
    working_dir: /app # Set the working directory to /app
    command: sh -c 'pnpm i && pnpm dev'
